### ISSUE TITLE
Set up sponsorship in Github

### ISSUE THREAD

**Issue by mike-audi** [tiki/.github#5]
If possible we want this set up at the org level. 

Requires a corresponding Stripe account to be created 

## Tasks

- [x] Create Stripe Connect account
- [x] Link Stripe account
- [ ] Fill out profile details
- [ ] Submit application

**Comment by timoguin** [comment]
We got initial approval for the `tiki` org. Need to finish filling out the profile, connect a Stripe account, and submit the final application.

![Screenshot_20221224_075056](https://user-images.githubusercontent.com/671968/209465747-5b56c627-3897-41f3-a896-d75d975475b2.png)

**Comment by mike-audi** [comment]
@timoguin I set up our Stripe account. Please take a stab at a fun profile/goals/tiers :)

**Comment by timoguin** [comment]
> @timoguin I set up our Stripe account. Please take a stab at a fun profile/goals/tiers :)

Can I make "bout a milli" one of the tiers?

**Comment by mike-audi** [comment]
completed.
