### ISSUE TITLE
Update the AWS Org management in 

### ISSUE THREAD

**Issue by ricardobrg** [tiki/.github#63]
### Description

Plan and update the AWS Org management using Control Tower.

### Tasks

- [x] Define the Org structure
- [x] Update the management services from org formation to control tower
- [x] Deploy the new accounts structure
